{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "logpilot.fullname" . }}-role
  labels:
    {{- include "logpilot.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "logpilot.fullname" . }}-rolebinding
  labels:
    {{- include "logpilot.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "logpilot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "logpilot.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}